### ISSUE TITLE
Labeling the Session

### ISSUE THREAD

**Issue by howard9199** [hinagiku-dev/Hinagiku#113]
Host can label the session, which can be used for classification. Ex: different classes

**Comment by TakalaWang** [comment]
@180079995 I have done for update labels API in Branch [113-labeling-the-session](https://github.com/hinagiku-dev/Hinagiku/tree/113-labeling-the-session), I need frontend.

**Comment by TakalaWang** [comment]
update labels API:
method: PUT
endpoint: src/routes/api/session/[id]/label/
body: {
    labels: string[]
}
