### ISSUE TITLE
Add token limit

### ISSUE THREAD

**Issue by TakalaWang** [hinagiku-dev/Hinagiku#120]
The document too long would lead to large token consume rapidly.
We need limit document size or token size to prevent it.
The chat period also should be fix.

**Comment by TakalaWang** [comment]
We need document text limit, it assign for @ryanlinjui.
Frontend also need a limit, it assign for @180079995.

**Comment by ryanlinjui** [comment]
@TakalaWang used by pdf trimming to 10000 characters length #122 
Please review it first before doing merge

**Comment by ryanlinjui** [comment]
### document text limit
solved by trimming pdf content in 10000 length #123
