### ISSUE TITLE
[Bug] Template with title in english characters without spaces will cause UI issue

### ISSUE THREAD

**Issue by NaoCoding** [hinagiku-dev/Hinagiku#126]
I found that template with title written in english characters which does not include space will lead to serious frontend UI issue. If someone create a large quantity of templates which poccess title similar to following example, it will seriously affect every user's user experience.

![chrome-capture-2024-12-27](https://github.com/user-attachments/assets/b0f8f612-fe5b-4e64-af5f-ba074e8f5b44)

**Comment by howard9199** [comment]
Thank you for your contribution, we will solve it ASAP :)
