### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by NaoCoding** [hinagiku-dev/Hinagiku#24]
I was trying and experiencing the Hinagiku and accidentally misclicked the clear cookie function of my chrome extension.
It is reasonable that the create template and some other bottons cannot be clicked. 
However, I found that if the cookie session was cleared after login, the frontend won't detect and replace some elements such as
* The `Welcome, {username} Logout` back to Login with Google Icon.
* nav `{username}` and dashboard to `Please Login First` with Google Icon.

Not sure if this is "defined " as a bug or an user bahavior issue.

![chrome-capture-2024-12-15](https://github.com/user-attachments/assets/5132257b-7edb-4b34-9e8d-334e797fbe1e)

The other serious bug is that the username length is not limited and can cause frontend width issue.
Update * :  this can cause a serious issue and cover all the bottons and functions.
I found that after entering too long username will crash the whole website. (browser out of memory error)

![chrome-capture-2024-12-15 (1)](https://github.com/user-attachments/assets/4e3d9382-04d6-4c5e-88de-5644438c4283)

**Comment by JacobLinCool** [comment]
Thanks for your invaluable report.

@howard9199 would you like to handle this one?

**Comment by JacobLinCool** [comment]
I'll be in-charge of this.
