### ISSUE TITLE
File Resource Upload

### ISSUE THREAD

**Issue by JacobLinCool** [hinagiku-dev/Hinagiku#27]
Users should be able to upload pdf as the discussion resource.

**Comment by JacobLinCool** [comment]
@ryanlinjui can you update the status of this feature here?

**Comment by ryanlinjui** [comment]
Yeah. Except to finish this week. I have final exam tomorrow.

**Comment by ryanlinjui** [comment]
I mean "today".

**Comment by JacobLinCool** [comment]
Take your time and feel free to share any screenshot or progress here after the exam.

**Comment by JacobLinCool** [comment]
Welcome back @ryanlinjui 

Do you have any progress on this?

**Comment by ryanlinjui** [comment]
#37
