### ISSUE TITLE
8. Offensive Language in Discussions:

### ISSUE THREAD

**Issue by Buffett111** [hinagiku-dev/Hinagiku#80]
The group discussion area currently allows inappropriate or offensive language such as "I will kill your family" or "I will rape you." A content filter for discussions is necessary.

**Comment by Buffett111** [comment]
@TakalaWang Can you use LLM to block the content of the Group discussion?
The picture shows a discussion about me playing the role of a perverted murderer.
![image](https://github.com/user-attachments/assets/62f37ccc-18b4-499c-b12f-73ca1000f92e)

**Comment by TakalaWang** [comment]
Did you think that we should still save offensive sentence in DB?
